Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -28,18 +28,13 @@ jobs:
         while (!(Test-Path "compile.log")) { Start-Sleep -Seconds 5}
       timeout-minutes: 20
 
-    - name : Get build result
-      run: Get-Content "compile.log"
-      
-    - name : Check artifact
-      run: if (!(Test-path "ECB-Cont.exe")) { Write-Error "Workflow failed, check the VB6 compile.log file"; exit 1 }
+    - name : Check build result
+      run: |
+        Get-Content "compile.log"
+        run: if (!(Test-path "ECB-Cont.exe")) { Write-Error "Workflow failed, check the VB6 compile.log file"; exit 1 }
 
     - name: Upload artifacts
       uses: actions/upload-artifact@v4.6.0
       with:
         name: artifact
         path: ECB-Cont.exe
-
-    - name : Clean workspace
-      run: if ((Test-path "C:\Runners\ECB_Cont\_work\ecb_cont\")) { Get-ChildItem "C:\Runners\ECB_Cont\_work\ecb_cont\" | Remove-Item -Recurse -Force }
-        
